kind: Ingress
apiVersion: networking.k8s.io/v1beta1
metadata:
  name: ingress-service
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web

spec:
  rules:
    - host: dev.api.kamilwronka.dev
      http:
        paths:
          - path: /auth-service
            backend:
              serviceName: auth-srv
              servicePort: 80
