kind: IngressRoute
apiVersion: traefik.containo.us/v1alpha1
metadata:
  name: ingress-service

spec:
  entryPoints:
    - websecure
    - web
  routes:
    - match: Host(`dev.api.kamilwronka.dev`) && PathPrefix(`/auth-service`)
      kind: Rule
      services:
        - name: auth-srv
          port: 80
      middlewares:
        - name: stripprefix
          namespace: default
  tls:
    certResolver: resolver
    domains:
      - main: kamilwronka.dev
        sans:
          - dev.api.kamilwronka.dev
