apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopn-cms-depl
spec:
  replicas: 2
  selector:
    matchLabels:
      app: shopn-cms
  template:
    metadata:
      labels:
        app: shopn-cms
    spec:
      containers:
        - name: shopn-cms
          image: kamilwronka7/shopn-cms
          ports:
            - containerPort: 80
          env:
            - name: CMS_MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: cms-mongodb-uri
                  key: CMS_MONGODB_URI

---
apiVersion: v1
kind: Service
metadata:
  name: shopn-cms-srv
spec:
  selector:
    app: shopn-cms
  ports:
    - name: shopn-cms
      protocol: TCP
      port: 80
      targetPort: 80
