apiVersion: apps/v1
kind: Deployment
metadata:
  name: dashboard-depl
spec:
  replicas: 4
  selector:
    matchLabels:
      app: dashboard
  template:
    metadata:
      labels:
        app: dashboard
    spec:
      containers:
        - name: dashboard
          image: kamilwronka7/shopn-app
          ports:
            - containerPort: 80
---

---
apiVersion: v1
kind: Service
metadata:
  name: dashboard-srv
spec:
  selector:
    app: dashboard
  ports:
    - name: dashboard
      protocol: TCP
      port: 80
      targetPort: 80
