FROM node:12.16.3

ARG NODE_ENV
ARG DB_PORT
ARG DB_HOST
ARG DB_NAME
ARG PORT

WORKDIR /usr/src/app
COPY package.json yarn.lock ./
RUN yarn
COPY . ./
RUN yarn build

ENTRYPOINT [ "yarn", "start:prod" ]