
FROM node:14.1.0-alpine

ARG NODE_ENV
ARG MAILGUN_HOST
ARG MAILGUN_API_KEY
ARG MAILGUN_DOMAIN
ARG DOMAIN_NAME
ARG MAIL_SERVICE_PORT
ARG REDIS_PORT
ARG REDIS_HOST

WORKDIR /usr/src/app
COPY package.json yarn.lock ./
RUN yarn
COPY . ./
RUN yarn build
RUN yarn copy-templates
RUN yarn copy-translations

ENTRYPOINT [ "yarn", "start:prod" ]