FROM node:14.1.0-alpine

ENV MAILGUN_HOST=changeme
ENV MAILGUN_API_KEY=changeme
ENV MAILGUN_DOMAIN=changeme
ENV DOMAIN_NAME=changeme
ENV REDIS_PORT=6379
ENV REDIS_HOST=localhost

WORKDIR /usr/src/app
COPY package.json yarn.lock ./
RUN yarn
ENV NODE_ENV=production

COPY . .

RUN yarn build
RUN yarn copy-templates
RUN yarn copy-translations

ENTRYPOINT [ "yarn", "start:prod" ]