name: deploy-auth-service

env:
  KUBECONFIG: /home/deploy/config
  KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}

on:
  push:
    branches:
      - master
    # paths:
    #   - "auth-service/**"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # - run: cd auth-service && docker build -f Dockerfile.prod -t kamilwronka7/auth-service .
      # - run: docker login -u $DOCKER_ID -p $DOCKER_PASS
      #   env:
      #     DOCKER_ID: ${{ secrets.DOCKER_ID }}
      #     DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
      # - run: docker push kamilwronka7/auth-service
      - run: sudo mkdir -p /home/deploy
      - uses: timheuer/base64-to-file@v1
        id: write_file
        with:
          fileName: 'config'
          encodedString: ${{ secrets.KUBE_CONFIG_DATA }}
      - uses: actions/checkout@v2
      - run: cp ${{ steps.write_file.outputs.filePath }} /home/deploy
      - run: kubectl get all
