name: deploy-auth-service

on:
  push:
    branches:
      - master
    # paths:
    #   - "auth-service/**"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # - run: cd auth-service && docker build -f Dockerfile.prod -t kamilwronka7/auth-service .
      # - run: docker login -u $DOCKER_ID -p $DOCKER_PASS
      #   env:
      #     DOCKER_ID: ${{ secrets.DOCKER_ID }}
      #     DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
      # - run: docker push kamilwronka7/auth-service
      - uses: azure/k8s-set-context@v1
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
        with:
          method: kubeconfig
          kubeconfig: $KUBE_CONFIG_DATA
        id: setcontext
      - run: kubectl get all
